[package]
name        = "rtpv-core"
description = "Core library for rtpv — crypto, store, OTP, audit, config"
version.workspace    = true
edition.workspace    = true
authors.workspace    = true
license.workspace    = true
rust-version.workspace = true

[features]
default     = ["age-native", "clipboard"]
age-native  = ["age"]
gpg-compat  = []
clipboard   = ["arboard"]

[dependencies]
serde.workspace         = true
serde_json.workspace    = true
toml.workspace          = true
anyhow.workspace        = true
thiserror.workspace     = true
rand.workspace          = true
zxcvbn.workspace        = true
directories.workspace   = true
fuzzy-matcher.workspace = true
chrono.workspace        = true
base64.workspace        = true
base32.workspace        = true
url.workspace           = true
sha1.workspace          = true
walkdir.workspace       = true
urlencoding.workspace   = true
shellexpand.workspace   = true
totp-rs.workspace       = true
git2.workspace          = true
notify-rust.workspace   = true
dirs.workspace          = true
tempfile.workspace      = true
reqwest.workspace       = true
age                     = { workspace = true, optional = true }
arboard                 = { workspace = true, optional = true }
csv                     = "1"
tar                     = "0.4"
